console.log(typeof 0);           // "number"
console.log(typeof 3.14);        // "number"
console.log(typeof -7);          // "number"
console.log(typeof NaN);        // "number"
console.log(typeof Math);        // "object"
console.log(typeof 10n);        // "bigint"
console.log(typeof true);        // "boolean"
console.log(typeof false);       // "boolean"
console.log(typeof "Hello");    // "string"
console.log(typeof '');         // "string"console.log(typeof `Template`); // "string"
console.log(typeof undefined);   // "undefined"
console.log(typeof null);        // "object"
console.log(typeof Symbol());    // "symbol"
console.log(typeof function(){}); // "function"
console.log(typeof []);          // "object"
console.log(typeof {});          // "object"
console.log(typeof new Date()); // "object"
console.log(typeof /abc/);      // "object" 
console.log(typeof Date.now()); // "number"
console.log(typeof (0) == typeof('Rahul')) // false
